title: Writing Bits
email: philipp.fahlteich@gmail.com
description: Source code and other novels by Philipp Fahlteich
baseurl: ""
url: ""
github_username:  Faltenreich
twitter_username: faltendev

theme: minima
plugins:
  - jekyll-feed