title: Writing Bits
author:
  name: Philipp Fahlteich
  email: "philipp.fahlteich@gmail.com"
description: Source code and other novels
baseurl: ""
url: ""
github_username: 
twitter_username: 

theme: minima

minima:
  social_links:
    twitter: faltendev
    github: Faltenreich
    stackoverflow: "3269827"
    linkedin: philipp-fahlteich

plugins:
  - jekyll-feed

kramdown:
  hard_wrap: true

collections:
  poems:
    output: true