title: Writing Bits
author:
  name: Philipp Fahlteich
  title: Mobile Developer
  email: "philipp.fahlteich@gmail.com"
  location: Türkheim, Bavaria, Germany
description: Source code and other novels
baseurl: ""
url: ""

plugins:
  - jekyll-remote-theme
  - jekyll-feed


header_pages:
  - software.md
  - poetry.md
  - imprint.md

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    twitter: faltendev
    github: Faltenreich
    stackoverflow: "3269827"
    linkedin: philipp-fahlteich
    xing: Philipp_Fahlteich

kramdown:
  hard_wrap: true

collections:
  poetry:
    output: true