title: Writing Bits
url: https://writingbits.de
author:
  name: Philipp Fahlteich
  title: Mobile Developer
  email: philipp.fahlteich@gmail.com
  location: Türkheim, Bavaria, Germany
future: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed

header_pages:
  - blog.md
  - software.md
  - poetry.md

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/Faltenreich"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/philipp-fahlteich"
    - title: XING
      icon: xing
      url: "https://www.xing.com/profile/Philipp_Fahlteich"
    - title: E-Mail
      icon: envelope
      fa_namespace: regular
      url: "mailto:philipp.fahlteich@gmail.com"
      
kramdown:
  hard_wrap: true

collections:
  poetry:
    output: true