title: Writing Bits
email: philipp.fahlteich@gmail.com
description: Source code and other novels by Philipp Fahlteich
baseurl: ""
url: ""
twitter_username: faltendev
github_username:  Faltenreich

theme: minima
plugins:
  - jekyll-feed