title: Writing Bits
author:
  name: Philipp Fahlteich
  title: Mobile Developer
  email: "philipp.fahlteich@gmail.com"
  location: Türkheim, Bavaria, Germany
description: "Source code and other novels"
baseurl: ""
url: ""
future: true

plugins:
  - jekyll-remote-theme
  - jekyll-feed

header_pages:
  - blog.md
  - software.md
  - poetry.md

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/Faltenreich"
      title: GitHub
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/3269827/philipp-fahlteich"
      title: Stack Overflow
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/philipp-fahlteich"
      title: LinkedIn
    - platform: xing
      user_url: "https://www.xing.com/profile/Philipp_Fahlteich"
      title: XING
    - platform: mail
      user_url: "mailto:philipp.fahlteich@gmail.com"
      title: E-Mail
    - platform: rss
      user_url: "feed.xml"
      title: RSS

kramdown:
  hard_wrap: true

collections:
  poetry:
    output: true