title: Writing Bits
author:
  name: Philipp Fahlteich
  email: "philipp.fahlteich@gmail.com"
description: Source code and other novels
baseurl: ""
url: ""
github_username: 
twitter_username:

plugins:
  - jekyll-remote-theme
  - jekyll-feed


header_pages:
  - blog.md
  - profession.md
  - software.md
  - poems.md

remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    twitter: faltendev
    github: Faltenreich
    stackoverflow: "3269827"
    linkedin: philipp-fahlteich

kramdown:
  hard_wrap: true

collections:
  poems:
    output: true