title: Writing Bits
email: philipp.fahlteich@gmail.com
description: Source code and other novels by Philipp Fahlteich
baseurl: ""
url: ""
github_username:  Faltenreich
twitter_username: faltendev
color-scheme: auto
remote_theme: BDHU/minimalist
plugins:
  - jekyll-feed
  - jekyll-remote-theme